// Albums Data - Centralized data structure for all Jay Chou albums
const albumsData = [
    {
        id: 1,
        year: 2000,
        title: "JAY",
        image: "https://cdn.albumoftheyear.org/album/178397-jay.jpg",
        description: "Jay is the debut studio album by Taiwanese singer Jay Chou, released on 7 November 2000 by BMG Taiwan. The album was nominated for five Golden Melody Awards and won for Best Pop Vocal Album. The album also won an IFPI Hong Kong Top Sales Music Award for Top 10 Best Selling Mandarin Albums of the Year. The track, \"Adorable Lady\", is listed at number 74 on the 2000s Hit FM Top 100 Singles of the Year chart. The track, \"Starry Mood\", is also listed at number 80 on the 2001's chart.",
        fullTitle: "2000年第1張專輯:《周杰倫 JAY CHOU》同名專輯 (CD+DVD)-台灣原版進口 Jay Chou 1st album",
        price: "$24.99",
        diskNumber: 1,
        tracks: [
            { number: 1, en: "Adorable Lady", cn: "可愛女人" },
            { number: 2, en: "Perfectionism", cn: "完美主義" },
            { number: 3, en: "Starry Mood", cn: "星晴" },
            { number: 4, en: "Basketball Match", cn: "鬥牛" },
            { number: 5, en: "Black Humor", cn: "黑色幽默" },
            { number: 6, en: "Istanbul", cn: "伊斯坦堡" },
            { number: 7, en: "Ancient Indian Turtledove", cn: "印地安老斑鳩" },
            { number: 8, en: "Tornado", cn: "龍捲風" },
            { number: 9, en: "Counter-clockwise Clock", cn: "反方向的鐘" },
            { number: 10, en: "Wife", cn: "娘子" }
        ]
    },
    {
        id: 2,
        year: 2001,
        title: "FANTASY",
        image: "https://i1.sndcdn.com/artworks-KDKU0cmKngZOjLdg-O7hHSw-t500x500.jpg",
        description: "Fantasy is the second studio album, released on 14 September 2001 by BMG Taiwan. The album was nominated for ten Golden Melody Awards and won five awards, including Best Pop Vocal Album, Best Album Producer, and Best Composer. The album also won for an IFPI Hong Kong Top Sales Music Award for Top 10 Best Selling Mandarin Albums of the Year. The tracks, \"Simple Love\" and \"I Find It Hard to Say\", are listed at number 2 and number 17 respectively on the 2001's Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2001年第2張專輯：《范特西》(CD+寫真)-台灣原版進口 Jay Chou 2nd album",
        price: "$24.99",
        diskNumber: 2,
        tracks: [
            { number: 1, en: "Love before BC", cn: "愛在西元前" },
            { number: 2, en: "Dad, I'm home", cn: "爸，我回來了" },
            { number: 3, en: "Simple Love", cn: "簡單愛" },
            { number: 4, en: "Ninja", cn: "忍者" },
            { number: 5, en: "Hard to Say it Out", cn: "開不了口" },
            { number: 6, en: "Shanghai 1943", cn: "上海一九四三" },
            { number: 7, en: "Sorry", cn: "對不起" },
            { number: 8, en: "William Castle", cn: "威廉古堡" },
            { number: 9, en: "Nunchucks", cn: "雙截棍" },
            { number: 10, en: "Silence", cn: "安靜" }
        ]
    },
    {
        id: 3,
        year: 2002,
        title: "THE EIGHT DIMENSIONS",
        image: "https://i1.sndcdn.com/artworks-HoQ9l56book8-0-t500x500.jpg",
        description: "The Eight Dimensions is the third studio album, released on 18 July 2002 by BMG Taiwan. The album was nominated for five Golden Melody Awards. The album also won for an IFPI Hong Kong Top Sales Music Award for Best Selling Mandarin Album of the Year. The tracks, \"Secret Sign\", \"Back to the Past\", and \"The Final Battle\", are listed at number 1, number 5, and number 42 respectively on the 2002's Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2002年第3張專輯：《八度空間》(CD+DVD)-台灣原版進口 Jay Chou 3rd album",
        price: "$24.99",
        diskNumber: 3,
        tracks: [
            { number: 1, en: "Half-beast Human", cn: "半獸人" },
            { number: 2, en: "Peninsula Ironbox", cn: "半島鐵盒" },
            { number: 3, en: "Secret Sign", cn: "暗號" },
            { number: 4, en: "Dragon Fist", cn: "龍拳" },
            { number: 5, en: "The Train's Destination", cn: "火車叨位去" },
            { number: 6, en: "Split/Leave", cn: "分裂/离开" },
            { number: 7, en: "Grandpa's Tea", cn: "爺爺泡的茶" },
            { number: 8, en: "Back to the Past", cn: "回到過去" },
            { number: 9, en: "Little Blacksmith in Milan", cn: "米蘭小鐵匠" },
            { number: 10, en: "The Last Battle", cn: "最後的戰役" }
        ]
    },
    {
        id: 4,
        year: 2003,
        title: "YE HUI-MEI",
        image: "https://i1.sndcdn.com/artworks-3YBX35mQzzI4PeKj-bQuXfw-t500x500.jpg",
        description: "Yeh Hui-Mei is the fourth studio album, released on 29 July 2003 by Alfa Music. The album was named after his mother. The album was nominated for eight Golden Melody Awards and won two awards, including Best Pop Vocal Album and Best Music Video for \"Class 3-2\". The album also won an IFPI Hong Kong Top Sales Music Award for Best Selling Mandarin Album of the Year. The tracks, \"Sunny Day\", \"Her Eyelashes\", and \"East Wind Breaks\", are listed at number 2, number 15, and number 41 respectively on the 2003's Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2003年第4張專輯：《葉惠美》(CD+DVD)-台灣原版進口 Jay Chou 4th album",
        price: "$24.99",
        diskNumber: 4,
        tracks: [
            { number: 1, en: "In The Name of Father", cn: "以父之名" },
            { number: 2, en: "Coward", cn: "懦夫" },
            { number: 3, en: "Sunny Day", cn: "晴天" },
            { number: 4, en: "Class 3-2", cn: "三年二班" },
            { number: 5, en: "Dong Feng Po", cn: "東風破" },
            { number: 6, en: "You Hear Me", cn: "妳聽得到" },
            { number: 7, en: "Same Tone", cn: "同一種調調" },
            { number: 8, en: "Her Eyelashes", cn: "她的睫毛" },
            { number: 9, en: "Cliff", cn: "愛情懸崖" },
            { number: 10, en: "Terrace Field", cn: "梯田" },
            { number: 11, en: "Double Blade", cn: "雙刀" }
        ]
    },
    {
        id: 5,
        year: 2004,
        title: "COMMON JASMINE ORANGE",
        image: "https://i1.sndcdn.com/artworks-91120f5f-e17a-4bb7-aec3-771484b6e23c-0-t500x500.jpg",
        description: "Common Jasmine Orange is the fifth studio album, released on 3 August 2004 by Sony Music Taiwan. The album was nominated for six Golden Melody Awards. The album won for an IFPI Hong Kong Top Sales Music Award for Best Selling Mandarin Album of the Year. According to IFPI, The album is also listed at number 43 of 2004's global best-selling albums. The tracks, \"Common Jasmine Orange\", \"Excuse\", and \"Wounds of War\", are listed at number 1, number 10, and number 88 respectively on the 2004's Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2004年第5張專輯：《七里香》(CD+DVD)-台灣原版進口 Jay Chou 5th album",
        price: "$24.99",
        diskNumber: 5,
        tracks: [
            { number: 1, en: "My Territory", cn: "我的地盤" },
            { number: 2, en: "Common Jasmine Orange", cn: "七里香" },
            { number: 3, en: "Excuse", cn: "藉口" },
            { number: 4, en: "Grandma", cn: "外婆" },
            { number: 5, en: "General", cn: "將軍" },
            { number: 6, en: "Chaotic Dance", cn: "亂舞春秋" },
            { number: 7, en: "Struggle", cn: "困獸之鬥" },
            { number: 8, en: "Fun Fair", cn: "園遊會" },
            { number: 9, en: "Wounds of War", cn: "止戰之殤" },
            { number: 10, en: "Step Aside", cn: "擱淺" }
        ]
    },
    {
        id: 6,
        year: 2005,
        title: "NOVEMBER'S CHOPIN",
        image: "https://i1.sndcdn.com/artworks-79371e84-1589-47af-9db0-f7d21420915e-0-t500x500.jpg",
        description: "November's Chopin is the sixth studio album, released on 1 November 2005 by Sony Music Taiwan. The album was nominated for two Golden Melody Awards. The album won for an IFPI Hong Kong Top Sales Music Award for Top 10 Best Selling Mandarin Albums of the Year. The track, \"Drifting\", was nominated a Golden Horse Award for Best Original Film Song and a Hong Kong Film Award for Best Original Film Song.",
        fullTitle: "2005年第6張專輯：《11月的蕭邦》(CD+DVD)-台灣原版進口 Jay Chou 6th album",
        price: "$24.99",
        diskNumber: 6,
        tracks: [
            { number: 1, en: "Nocturne", cn: "夜曲" },
            { number: 2, en: "Blue Storm", cn: "藍色風暴" },
            { number: 3, en: "Hair Like Snow", cn: "髮如雪" },
            { number: 4, en: "Black Sweater", cn: "黑色毛衣" },
            { number: 5, en: "Surrounded", cn: "四面楚歌" },
            { number: 6, en: "Maple Leaf", cn: "楓" },
            { number: 7, en: "Romantic Cellphone", cn: "浪漫手機" },
            { number: 8, en: "Against", cn: "逆鱗" },
            { number: 9, en: "Malt Sugar", cn: "麥芽糖" },
            { number: 10, en: "Coral Sea", cn: "珊瑚海" },
            { number: 11, en: "Drifting", cn: "飄移" },
            { number: 12, en: "All the Way North", cn: "一路向北" }
        ]
    },
    {
        id: 7,
        year: 2006,
        title: "STILL FANTASY",
        image: "https://1.bp.blogspot.com/-qegcwu0rGP8/WWaKPzAgJfI/AAAAAAAAV6s/EVNiKxTnuZcCNWmH7BmdL-kThuVcGqCIwCPcBGAYYCw/s640/folder.jpg",
        description: "Still Fantasy is the seventh studio album, released on 5 September 2006 by Sony Music Taiwan & Alfa Music. The album was nominated for three Golden Melody Awards. The album also won an IFPI Hong Kong Top Sales Music Award for Best Selling Mandarin Album of the Year. The track, \"Chrysanthemum Terrace,\" won a Hong Kong Film Award for Best Original Film Song. The tracks, \"Far Away,\" \"Listen to Mom,\" and \"White Windmill,\" are listed at number 2, number 8 and number 53 respectively on 2006's Hit FM Top Singles of the Year chart.",
        fullTitle: "2006年第7張專輯：《依然范特西》(CD+DVD)-台灣原版進口 Jay Chou 7th album",
        price: "$24.99",
        diskNumber: 7,
        tracks: [
            { number: 1, en: "Chapter Seven", cn: "夜的第七章" },
            { number: 2, en: "Listen to Mom", cn: "聽媽媽的話" },
            { number: 3, en: "Far Away", cn: "千里之外" },
            { number: 4, en: "Chinese Herbal Manual", cn: "本草綱目" },
            { number: 5, en: "A Step Back", cn: "退後" },
            { number: 6, en: "Moulin Rouge", cn: "紅模仿" },
            { number: 7, en: "Rainy Mood", cn: "心雨" },
            { number: 8, en: "White Windmill", cn: "白色風車" },
            { number: 9, en: "Rosemary", cn: "迷迭香" },
            { number: 10, en: "Chrysanthemum Terrace", cn: "菊花台" }
        ]
    },
    {
        id: 8,
        year: 2007,
        title: "ON THE RUN!",
        image: "https://i1.sndcdn.com/artworks-16d4c998-8307-431e-a230-b2c56e68b1eb-0-t500x500.jpg",
        description: "On the Run! is the eighth studio album, released on 1 November 2007 by JVR Music. The album was nominated for five Golden Melody Awards and won Song of the Year, Best Composer, and Best Lyricist for \"Blue and White Porcelain\". The album also won an IFPI Hong Kong Top Sales Music Award for Top 10 Best Selling Mandarin Album of the Year. The tracks, \"Cowboy is Very Busy\", \"Rainbow\", and \"Sunshine Nerd\", are listed at number 11, number 28, and number 59 respectively on the 2010s Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2007年第8張專輯：《我很忙》(CD+DVD)-台灣原版進口 Jay Chou 8th album",
        price: "$24.99",
        diskNumber: 8,
        tracks: [
            { number: 1, en: "Cowboy On The Run", cn: "牛仔很忙" },
            { number: 2, en: "Rainbow", cn: "彩虹" },
            { number: 3, en: "Blue and White Porcelain", cn: "青花瓷" },
            { number: 4, en: "Sunshine Nerd", cn: "陽光宅男" },
            { number: 5, en: "A Dandelion's Promise", cn: "蒲公英的約定" },
            { number: 6, en: "Incomparable", cn: "無雙" },
            { number: 7, en: "Not Good Enough For You/Distance", cn: "我不配/距離" },
            { number: 8, en: "Pull Apart", cn: "扯" },
            { number: 9, en: "Sweet", cn: "甜甜的" },
            { number: 10, en: "The Longest Movie", cn: "最長的電影" }
        ]
    },
    {
        id: 9,
        year: 2008,
        title: "CAPRICORN",
        image: "https://i1.sndcdn.com/artworks-Pcby8z7ZTllNMQd1-sSHcpA-t500x500.jpg",
        description: "Capricorn is the ninth studio album, released on 14 October 2008 by JVR Music. At the 20th Golden Melody Awards, the album was nominated for eight awards, winning Best mandarin Male Singer, Song of the Year for \"Fragrant Rice\", Best Music Video for \"Magician\". The tracks, \"Fragrant Rice\", \"Give Me the Time of a Song\", and \"The Promised Love\", are listed at number 3, number 17, and number 56 respectively on the 2008's Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2008年第9張專輯：《魔杰座》-台灣原版進口 Jay Chou 9th album",
        price: "$24.99",
        diskNumber: 9,
        tracks: [
            { number: 1, en: "Dragon Rider", cn: "龍戰騎士" },
            { number: 2, en: "Give Me the Time of a Song", cn: "給我一首歌的時間" },
            { number: 3, en: "Snake Dance", cn: "蛇舞" },
            { number: 4, en: "Floral Sea", cn: "花海" },
            { number: 5, en: "Magician", cn: "魔術先生" },
            { number: 6, en: "The Promised Love", cn: "說好的幸福呢" },
            { number: 7, en: "Orchid Pavilion", cn: "蘭亭序" },
            { number: 8, en: "Drifting Poet", cn: "流浪诗人" },
            { number: 9, en: "Time Machine", cn: "時光機" },
            { number: 10, en: "Uncle Joker", cn: "喬克叔叔" },
            { number: 11, en: "Rice Field", cn: "稻香" }
        ]
    },
    {
        id: 10,
        year: 2010,
        title: "THE ERA",
        image: "https://i.ebayimg.com/images/g/cVsAAOSwZdZcwTqY/s-l400.jpg",
        description: "The Era is the tenth studio album, released on 18 May 2010 by JVR Music and Sony Music Taiwan. The album was nominated for six Golden Melody Awards and won for Best Mandarin Male Singer, Best Mandarin album, and Best Musical Arrangement for \"Free Tutorial Video\". The tracks, \"Superman Can't Fly\", \"Rain Falls All Night\", and \"The Era\", are listed at number 2, number 10, and number 39 respectively on the 2010s Hit FM Top 100 Singles of the Year chart.",
        fullTitle: "2010年第10張專輯：《跨時代》-台灣原版進口 Jay Chou 10th album",
        price: "$24.99",
        diskNumber: 10,
        tracks: [
            { number: 1, en: "The Era", cn: "跨時代" },
            { number: 2, en: "Say Goodbye", cn: "說了再見" },
            { number: 3, en: "Fade Away", cn: "煙花易冷" },
            { number: 4, en: "Free Tutorial Video", cn: "免費教學錄影帶" },
            { number: 5, en: "Long Time No See", cn: "好久不見" },
            { number: 6, en: "Rain All Night", cn: "雨下一整晚" },
            { number: 7, en: "Hip-hop Flight Attendant", cn: "嘻哈空姐" },
            { number: 8, en: "Tears of Scattered Emotion", cn: "我落淚 情緒零碎" },
            { number: 9, en: "Diary of Love", cn: "愛的飛行日記" },
            { number: 10, en: "Self-directed Act", cn: "自導自演" },
            { number: 11, en: "Superman Can't Fly", cn: "超人不會飛" }
        ]
    },
    {
        id: 11,
        year: 2011,
        title: "WOW!",
        image: "https://cdn.albumoftheyear.org/album/221518-wow.jpg",
        description: "Wow! or known as Exclamation Point is the eleventh studio album, released on 11 November 2011 by JVR Music. The album was nominated for three Golden Melody Awards and won for Best Album Packaging.",
        fullTitle: "2011年第11張專輯：《驚歎號》-台灣原版進口 Jay Chou 11th album",
        price: "$24.99",
        diskNumber: 11,
        tracks: [
            { number: 1, en: "Exclamation Point", cn: "驚嘆號" },
            { number: 2, en: "Enchanting Melody", cn: "迷魂曲" },
            { number: 3, en: "Mine Mine", cn: "Mine Mine" },
            { number: 4, en: "Princess Syndrome", cn: "公主病" },
            { number: 5, en: "How Are You", cn: "你好嗎" },
            { number: 6, en: "Healing Rice Dumpling", cn: "療傷燒肉粽" },
            { number: 7, en: "Piano of Sorrow", cn: "琴傷" },
            { number: 8, en: "Sailor Afraid of Water", cn: "水手怕水" },
            { number: 9, en: "Not the End of the World", cn: "世界未末日" },
            { number: 10, en: "Shadow Play", cn: "皮影戲" },
            { number: 11, en: "Sports Car Model", cn: "超跑女神" }
        ]
    },
    {
        id: 12,
        year: 2012,
        title: "OPUS 12",
        image: "https://i1.sndcdn.com/artworks-5e4d1207-5ce4-4229-995f-8955964281ff-0-t500x500.jpg",
        description: "Opus 12, released on 28 December 2012 by JVR Music. The album was nominated for four Golden Melody Awards.",
        fullTitle: "2012年第12張專輯：《12新作》-台灣原版進口 Jay Chou 12th album",
        price: "$24.99",
        diskNumber: 12,
        tracks: [
            { number: 1, en: "Four Seasons Train", cn: "四季列車" },
            { number: 2, en: "Sign Language", cn: "手語" },
            { number: 3, en: "Eunuch with a Headache", cn: "公公偏頭痛" },
            { number: 4, en: "Obviously", cn: "明明就" },
            { number: 5, en: "Smile", cn: "傻笑" },
            { number: 6, en: "A Larger Cello", cn: "比較大的大提琴" },
            { number: 7, en: "Love You No Matter What", cn: "愛你沒差" },
            { number: 8, en: "Mundane Inn", cn: "紅塵客棧" },
            { number: 9, en: "Dream", cn: "夢想啟動" },
            { number: 10, en: "Big Ben", cn: "大笨鐘" },
            { number: 11, en: "You Are Everywhere", cn: "哪裡都是你" },
            { number: 12, en: "Ukulele", cn: "烏克麗麗" }
        ]
    },
    {
        id: 13,
        year: 2014,
        title: "AIYO, NOT BAD",
        image: "https://i1.sndcdn.com/artworks-1513cec2-e152-4d85-b700-620dc9ae54e7-0-t500x500.jpg",
        description: "Aiyo, Not Bad is the thirteenth studio album, released on 26 December 2014 by Sony Music Taiwan and JVR Music. The album was nominated for three Golden Melody Awards.",
        fullTitle: "2014年第13張專輯：《哎呦，不錯喔》-台灣原版進口 Jay Chou 13th album",
        price: "$24.99",
        diskNumber: 13,
        tracks: [
            { number: 1, en: "Yang-Ming Mountain", cn: "陽明山" },
            { number: 2, en: "Stolen Love", cn: "竊愛" },
            { number: 3, en: "What Kind of Man", cn: "算什麼男人" },
            { number: 4, en: "Passer-by", cn: "天涯過客" },
            { number: 5, en: "What's Wrong", cn: "怎麼了" },
            { number: 6, en: "One Breath", cn: "一口氣全唸對" },
            { number: 7, en: "I Want Summer", cn: "我要夏天" },
            { number: 8, en: "Handwritten Past", cn: "手寫的從前" },
            { number: 9, en: "Extra Large Shoes", cn: "鞋子特大號" },
            { number: 10, en: "Listen to Dad", cn: "聽爸爸的話" },
            { number: 11, en: "Mermaid", cn: "美人魚" },
            { number: 12, en: "Rhythm of the Rain", cn: "聽見下雨的聲音" }
        ]
    },
    {
        id: 14,
        year: 2016,
        title: "JAY CHOU'S BEDTIME STORIES",
        image: "https://i1.sndcdn.com/artworks-a60fd4e1-7901-4427-bd96-9aeec146eba8-0-t500x500.jpg",
        description: "Jay Chou's Bedtime Stories is the fourteenth studio album, released on 24 June 2016 by JVR Music. The album was nominated for three Golden Melody Awards.",
        fullTitle: "2016第14张專輯《周杰倫的床邊故事》-台灣原版進口 Jay Chou 14th album",
        price: "$24.99",
        diskNumber: 14,
        tracks: [
            { number: 1, en: "Bedtime Stories", cn: "床邊故事" },
            { number: 2, en: "Let's Go", cn: "說走就走" },
            { number: 3, en: "A Little Bit", cn: "一點點" },
            { number: 4, en: "Lover From a Previous Life", cn: "前世情人" },
            { number: 5, en: "Hero", cn: "英雄" },
            { number: 6, en: "Shouldn't Be", cn: "不該" },
            { number: 7, en: "Turkish Ice Cream", cn: "土耳其冰淇淋" },
            { number: 8, en: "Love Confession/Confession Balloon", cn: "告白氣球" },
            { number: 9, en: "Now You See Me", cn: "Now You See Me" },
            { number: 10, en: "Love Waste", cn: "愛情廢柴" }
        ]
    },
    {
        id: 15,
        year: 2022,
        title: "GREATEST WORKS OF ART",
        image: "https://m.media-amazon.com/images/I/51pRL1BlWcL._UXNaN_FMjpg_QL85_.jpg",
        description: "Greatest Works of Art is the fifteenth studio album by Taiwanese singer Jay Chou, released on 15 July 2022 through JVR Music. It is Chou's first album since his fourteenth studio album Jay Chou's Bedtime Stories and was preceded by five singles released from 2018 to 2022—\"Waiting for You\" with Gary Yang, \"If You Don't Love Me, It's Fine\", \"Won't Cry\" with Mayday vocalist Ashin, \"Mojito\" and the title track. The song \"I Truly Believe\" was released in 2019 as the theme for the 2019 Chinese action film Skyfire. The title track and \"Still Wandering\" also had music videos shot for them, which were released in July 2022.",
        fullTitle: "【預購】《最偉大的作品 Greatest Works Of Art》珍藏雙黑膠 Jay Chou 15th Vinyl (2LP)",
        price: "$79.99",
        diskNumber: 15,
        tracks: [
            { number: 1, en: "Intro", cn: "Intro" },
            { number: 2, en: "Greatest Works of Art", cn: "最偉大的作品" },
            { number: 3, en: "Still Wandering", cn: "還在流浪" },
            { number: 4, en: "Won't Cry", cn: "說好不哭" },
            { number: 5, en: "Cold Hearted", cn: "紅顏如霜" },
            { number: 6, en: "If You Don't Love Me, It's Fine", cn: "不愛我就拉倒" },
            { number: 7, en: "Mojito", cn: "Mojito" },
            { number: 8, en: "You Are The Firework That I Missed", cn: "錯過的煙火" },
            { number: 9, en: "Waiting for You", cn: "等你下課" },
            { number: 10, en: "Pink Ocean", cn: "粉色海洋" },
            { number: 11, en: "Reflection", cn: "倒影" },
            { number: 12, en: "I Truly Believe", cn: "I Truly Believe" }
        ]
    }
];

